In [1]:
import numpy as np


In [3]:
x = [1, 0, 0]
y = [0, 5, 6]
np.cross(x, y)

array([ 0, -6,  5])

In [6]:
real = False

In [7]:
aa  = np.array([1,2,3])
aa

array([1, 2, 3])

In [8]:
aa * real

array([0, 0, 0])

In [4]:
z = [.5,.3, .2]
# x = [.4999, .32001, .1999]
x = [.1,.51,.42]


z = z / np.linalg.norm(z)
x = x / np.linalg.norm(x)

In [5]:
y = np.cross(z,x)
y = y / np.linalg.norm(y)
y

array([ 0.08122723, -0.64304889,  0.76150526])

In [6]:
xb = np.cross(y,z)
xb = xb / np.linalg.norm(xb)
xb

array([-0.57923001,  0.59130874,  0.56111191])

In [125]:
# A = np.random.randint(0,323, (3,3))
A = np.array([[1,2,3],[3,5,6],[7,12,9]])
A, A.T

(array([[ 1,  2,  3],
        [ 3,  5,  6],
        [ 7, 12,  9]]),
 array([[ 1,  3,  7],
        [ 2,  5, 12],
        [ 3,  6,  9]]))

In [126]:
A_skew = A - A.T
A_sym = A + A.T
A_skew, A_sym

(array([[ 0, -1, -4],
        [ 1,  0, -6],
        [ 4,  6,  0]]),
 array([[ 2,  5, 10],
        [ 5, 10, 18],
        [10, 18, 18]]))

In [127]:
twoA = A_skew + A_sym
twoA

array([[ 2,  4,  6],
       [ 6, 10, 12],
       [14, 24, 18]])

In [128]:
.5 * twoA

array([[ 1.,  2.,  3.],
       [ 3.,  5.,  6.],
       [ 7., 12.,  9.]])

In [129]:
np.array_equal(A, .5 * twoA)

True

In [130]:
A_inv = np.linalg.inv(A)

In [131]:
A @ A_inv

array([[ 1.00000000e+00, -3.88578059e-16,  1.11022302e-16],
       [-1.11022302e-15,  1.00000000e+00,  4.44089210e-16],
       [-7.77156117e-16, -2.49800181e-15,  1.00000000e+00]])

In [132]:
A_inv @ A

array([[ 1.00000000e+00, -2.22044605e-15, -2.10942375e-15],
       [ 1.11022302e-16,  1.00000000e+00,  3.33066907e-16],
       [ 0.00000000e+00, -4.44089210e-16,  1.00000000e+00]])