In [1]:
import numpy as np

In [2]:
def get_line(x0, y0, z0, psi0, dT, TRACKING_TIME=40, SETTLE_TIME=20):
    # Trajectory definition
    
    m = 0.05

    tracking_time = np.arange(0, TRACKING_TIME, dT)
    settle_time = np.arange(TRACKING_TIME, TRACKING_TIME + SETTLE_TIME + 1, dT)

    time_vec = np.concatenate((tracking_time, settle_time))
    
    traj_x = np.concatenate((x0 + m*tracking_time, (x0 + m*TRACKING_TIME) * np.ones(len(settle_time))))
    traj_y = np.concatenate((y0 * np.ones(len(tracking_time)), y0 * np.ones(len(settle_time))))
    traj_z = np.concatenate((z0 * np.ones(len(tracking_time)), z0 * np.ones(len(settle_time))))
    traj_psi = np.concatenate((psi0 * np.ones(len(tracking_time)), psi0 * np.ones(len(settle_time))))
    
    traj_x_dot = np.concatenate((m * np.ones(len(tracking_time)), np.zeros(len(settle_time))))
    traj_y_dot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    traj_z_dot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    traj_psi_dot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    
    traj_x_ddot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    traj_y_ddot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    traj_z_ddot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    traj_psi_ddot = np.concatenate((np.zeros(len(tracking_time)), np.zeros(len(settle_time))))
    
    return (traj_x, traj_y, traj_z, traj_psi, traj_x_dot, traj_y_dot, traj_z_dot, traj_psi_dot, traj_x_ddot, traj_y_ddot, traj_z_ddot, traj_psi_ddot)


In [4]:
traj = get_line(0, 0, 0, 0, 0.01)

In [11]:
print(traj[0])

[0.e+00 5.e-04 1.e-03 ... 2.e+00 2.e+00 2.e+00]


In [13]:
TRACKING_TIME = 40
SETTLE_TIME = 20
dT = 0.01

In [14]:
tracking_time = np.arange(0, TRACKING_TIME, dT)
settle_time = np.arange(TRACKING_TIME, TRACKING_TIME + SETTLE_TIME + 1, dT)



In [34]:
(0.05*TRACKING_TIME) * np.ones(len(settle_time))

array([2., 2., 2., ..., 2., 2., 2.])

In [35]:
np.concatenate((0.05 * np.ones(len(tracking_time)), np.zeros(len(settle_time))))

array([0.05, 0.05, 0.05, ..., 0.  , 0.  , 0.  ])

In [17]:
settle_time[0:10]

array([40.  , 40.01, 40.02, 40.03, 40.04, 40.05, 40.06, 40.07, 40.08,
       40.09])